name: CI-CD

on:
  push:
    branches: [ master ]

# Set env variables
env:
  PROJECT_NAME: lawyer-document-search
  ARTIFACT_REGISTRY: frontend
  APP_NAME: frontend
  REGION: us-east1
  TAG: latest
  # Can't use it cs Actions is retarded and can't use ENV_VARS inside env
  # IMAGE_TAG: $REGION-docker.pkg.dev/$PROJECT_NAME/$ARTIFACT_REGISTRY/$APP_NAME:$TAG
    
jobs:
  setup:
    name: Setup environment 
    runs-on: ubuntu-latest
    steps:
      #Checks-out your repository under $GITHUB_WORKSPACE and sets WORKDIR to 
      # the repo so you can access files.
      - name: checkout-repo
        uses: actions/checkout@v2

      # Setup node environment
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: 17.x

      - name: install dependencies      
        run: |
          npm install
          npm ci
          npm run build

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2

      - run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2

      # Run in non-interactive mode
      - run: npm run test
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     # Clone the repository
  #     - name: checkout-repo
  #       uses: actions/checkout@v2

  #     - name: push heroku master
  #       uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
  #       with:
  #         heroku_api_key: $HEROKU_API_KEY
  #         heroku_app_name: $APP_NAME
  #         heroku_email: "woorkippo@gmail.com"
  #         usedocker: true